language: python
before_install:
    - MINICONDA_PATH=/home/travis/miniconda
    - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $MINICONDA_PATH
    - source $MINICONDA_PATH/etc/profile.d/conda.sh
    # TODO: it is currently failing on travis because conda wants to remove
    # setuptools which is a dependency of conda.
    # - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=3.6
    - conda activate testenv
    - pip install -r requirements.txt
    - pip install jupytext==1.3 yapf
script:
    - make --always-make
